idrac:
  host: 192.168.2.98
  username: root
  password: wang998321
shutdown:
  auto-mode: false
  fans-speed: 25
data-tier:
  - interval: 1s
    expire: 10m
  - interval: 5s
    expire: 6h
  - interval: 5m
    expire: 3d
  - interval: 1h
    expire: 14d

curve-points:
  default:
    '0': 10
    '40': 10
    '65': 30
    '80': 40
    '100': 100
  CPU1:
    '0': 10
    '40': 10
    '65': 30
    '80': 40
    '100': 100