idrac:
  host: 192.168.2.2
  username: root
  password: 123456
curve-points:
  '0': 10
  '40': 10
  '65': 30
  '80': 40
  '100': 100
app:
  showdown:
    auto-mode: false
    fans-speed: 20
test: 321
